//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.CalcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Calc", ConfigurationName="CalcServiceReference.CalcServiceSoap")]
    public interface CalcServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="Calc/Add", ReplyAction="*")]
        double Add(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="Calc/Sub", ReplyAction="*")]
        double Sub(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="Calc/Mul", ReplyAction="*")]
        double Mul(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="Calc/Div", ReplyAction="*")]
        double Div(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcServiceSoapChannel : Calculator.CalcServiceReference.CalcServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceSoapClient : System.ServiceModel.ClientBase<Calculator.CalcServiceReference.CalcServiceSoap>, Calculator.CalcServiceReference.CalcServiceSoap {
        
        public CalcServiceSoapClient() {
        }
        
        public CalcServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double x, double y) {
            return base.Channel.Add(x, y);
        }
        
        public double Sub(double x, double y) {
            return base.Channel.Sub(x, y);
        }
        
        public double Mul(double x, double y) {
            return base.Channel.Mul(x, y);
        }
        
        public double Div(double x, double y) {
            return base.Channel.Div(x, y);
        }
    }
}
